server:
  port: 5000

spring:
   application:
      name: masterdata-service
   config:
      import: configserver:http://localhost:8888
   zipkin:
      base-url: http://localhost:9411
      
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${random.uuid} 